openapi: 3.0.1
info:
  title: Carts API
  version: '1.0'

paths:
  /api/carts/{userId}/cart:
    get:
      summary: Get all carts
      tags:
        - Carts
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved carts.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        500:
          description: Internal server error.

    post:
      summary: Add a product to a cart
      tags:
        - Carts
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: Product added successfully.
        400:
          description: Bad request.
        500:
          description: Internal server error.

  /api/carts/{cid}:
    put:
      summary: Update all products of a cart
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      responses:
        202:
          description: Cart updated successfully.
        500:
          description: Internal server error.

  /api/carts/{userId}/{productId}:
    post:
      summary: Delete a product from a cart
      tags:
        - Carts
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Product deleted successfully.
        500:
          description: Internal server error.



components:
  schemas:
    User:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        age:
          type: integer
        rol:
          type: string
        cart:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer
        password:
          type: String
      
      example:
        _id: ObjectId('64c530d4febf9c7cb0afa10c')
        title: Example Product
        description: This is a description of the example product
        price: 100
        stock: 15
        category: test



      required:
        - title
        - description
        - price
        - category