openapi: 3.0.1
info:
  title: Products API
  version: '1.0'

paths:
  /api/products/:
    get:
      summary: Get all products
      security:
        - bearerAuth: []
      tags:
        - Products
      responses:
        200:
          description: List of products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        500:
          description: Server Error

    post:
      summary: Create a new product
      tags:
        - Products
      requestBody:
        requiered: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Products"
              
      responses:
        201:
          description: Product successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        400:
          description: Bad request
        500:
          description: Server Error

  /api/products/{pid}:
    get:
      summary: Get products by id
      tags:
        - Products

      parameters:
        - in: path
          name: uid
          required: true
          description: product id
          schema:
            type: string

      responses:
        200:
          description: Get products by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        404:
          description: Product not found
        500:
          description: Server Error

    delete:
      summary: Delete product by id
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: The ID of the product to delete
      responses:
        200:
          description: Product successfully deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "Product successfully deleted"
        404:
          description: Product not found
        500:
          description: Server Error




components:
  schemas:
    User:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        age:
          type: integer
        rol:
          type: string
        cart:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer
        password:
          type: String
      
      required:
        - first_name
        - last_name
        - email
        - password